name: 'Microsoft Teams Notification'
description: 'Send a custom notification message to a Microsoft Teams channel with GitHub repo details'
author: 'tomgelmersio'
branding:
  icon: message-circle
  color: purple 
inputs:
  github-token:
    description: 'GitHub Token'
    required: true 
  ms-teams-webhook-uri:
    description: 'Microsoft Teams Webhook URI'
    required: true 
  timezone:
    description: 'Timezone (ex. America/Denver)'
    required: false
  verbose-logging:
    description: 'Enable verbose logging'
    default: 'false'
    required: false
  state:
    description: 'Outcome of the step (ex. success, failure, cancelled)'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
